extends Node


signal HUD_set_countdown_text
signal HUD_set_timer_text
signal HUD_set_score_text
signal HUD_set_obstacle_text
signal HUD_set_faults_text
signal HUD_set_gait_text

signal LEV_change_level
signal LEV_level_changed

signal MUS_play_music
signal MUS_stop_music

signal OBS_start_course
signal OBS_reset_course
signal OBS_select_course
signal OBS_countdown_go
signal OBS_jumping_area_entered
signal OBS_jumping_area_exited
signal OBS_charge_jump
signal OBS_jump
signal OBS_crash
signal OBS_poles_dropped
signal OBS_points_earned
signal OBS_perfect_points_earned

signal SCO_record_score

signal SET_set_camera_speed_x
signal SET_set_camera_speed_y
signal SET_toggle_camera_invert_x
signal SET_toggle_camera_invert_y
signal SET_toggle_perfect_jump_particles
signal SET_set_general_volume
signal SET_set_music_volume
signal SET_set_sfx_volume
signal SET_set_ambience_volume
signal SET_set_game_window
signal SET_set_fps
signal SET_set_anti_aliasing
signal SET_toggle_shadows
signal SET_toggle_trees
signal SET_toggle_foliage
signal SET_toggle_nature_props

signal UI_open_menu
signal UI_toggle_hud
