extends Node


signal LEV_change_level
signal LEV_level_changed

signal OBS_restart_course
signal OBS_select_course
signal OBS_jumping_area_entered
signal OBS_jumping_area_exited
signal OBS_charge_jump
signal OBS_jump
signal OBS_crash
signal OBS_poles_dropped
signal OBS_points_earned
signal OBS_perfect_points_earned

signal UI_open_menu

signal HUD_set_countdown_text
signal HUD_set_timer_text
signal HUD_set_score_text
signal HUD_set_obstacle_text
signal HUD_set_faults_text
signal HUD_set_gait_text
